kind: Deployment
apiVersion: apps/v1
metadata:
  name: gracefulshutdown-deployment
  namespace: tiket-demo
  labels:
    app: gracefulshutdownLabel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gracefulshutdownLabel
  template:
    metadata:
      namespace: tiket-demo
      labels:
        app: gracefulshutdownLabel
    spec:
      terminationGracePeriodSeconds: 90
      containers:
      - name: gracefulshutdownapi
        image: gracefulshutdown:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          successThreshold: 2
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        lifecycle:
          preStop:
            httpGet:
              path: /pause
              port: 8080
        